server:
  port: 1111

spring:
  application:
    name: spring-test

  datasource:
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml